name: StarfunFreeCube
main: com.fancraft.freecube.FreeCubePlugin
version: 1.0.0
api-version: 1.9.4
author: FanCraft
commands:
  freecube:
    description: Gestion du mode FreeCube
    usage: /freecube
    permission: fancraft.freecube.use
permissions:
  fancraft.freecube.use:
    description: Accès général à FreeCube
    default: true
  fancraft.freecube.admin:
    description: Gestion FreeCube et retour hub
    default: op
  freecube.build:
    description: Permet de construire dans le monde FreeCube lorsque la protection est activée
    default: op
softdepend:
  - BKCommonLib
