name: FanCraftHikaBrain
main: com.fancraft.hikabrain.HikaBrainPlugin
version: 1.0.0
api-version: 1.9.4
author: FanCraft
commands:
  hikabrain:
    description: Gestion du mode HikaBrain
    usage: /hikabrain
softdepend:
  - BKCommonLib
